spring.application.name=docqa
gemini.api.key=AIzaSyBz9BQLa1ekK9x9jHZ0YDje14J72k7DPYI
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent
server.port=8080
